== Introduction and Goals

_Describes the relevant requirements and the driving forces that the software architects and development team must consider:_ 

* Underlying business goals 
* Essential features and functional requirements
* Quality goals for the architecture
* Relevant stakeholders and their expectations.

=== Requirements Overview

_Short description of the functional requirements, driving forces, extract or abstract of requirements. Link to existing requirements documents with version numbers._

*Contents*

_Short description of the functional requirements, driving forces, extract (or abstract) of requirements. Link to (hopefully existing) requirements documents (with version number and information where to find it)._

*Motivation*

_From the point of view of the end users a system is created or modified to improve support of a business activity and/or improve the quality._

*Form*

_Short textual description, probably in tabular use-case format. If requirements documents exist this overview should refer to these documents.
Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents._

=== Quality Goals

*Contents*

_The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don’t confuse them with project goals. They are not necessarily identical._

*Motivation*

_You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords. If you as an architect do not know how the quality of your work will be judged…_

*Form*

_A table with quality goals and concrete scenarios, ordered by priorities_

=== Stakeholders

*Content*

_Explicit overview of stakeholders - all persons, roles or organizations that_

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

*Motivation*

_You should know all parties involved in development of the system or
affected by the system. Otherwise, you may get nasty surprises later in
the development process. These stakeholders determine the extent and the
level of detail of your work and its results._

*Form*

_Table with role names, person names, and their expectations with respect
to the architecture and its documentation._

*Further Information*

_See_ https://docs.arc42.org/section-1/[Introduction and Goals] _in the
arc42 documentation._

[width="100%",cols="20%,40%,40%",options="header",]
|===
|Role/Name |Contact |Expectations
|_++<++Role-1++>++_ |_++<++Contact-1++>++_ |_++<++Expectation-1++>++_
|_++<++Role-2++>++_ |_++<++Contact-2++>++_ |_++<++Expectation-2++>++_
|===