== Cross-cutting Concepts

*Content*

_This section describes crosscutting concepts (practices, patterns,
regulations or solution ideas). Such concepts are often related to
multiple building blocks._

*Motivation*

_Concepts form the basis for *conceptual integrity* (consistency,
homogeneity) of the architecture. Thus, they are an important
contribution to achieve inner qualities of your system._

_This is the place in the template that we provided for a cohesive
specification of such concepts._

_Many of these concepts relate to or influence several of your building
blocks._

*Form*

_The form can be varied:_

* concept papers with any kind of structure
* example implementations,especially for technical concepts
* cross-cutting model excerpts or scenarios using notations of the
architecture views

*Structure*

_Pick *only* the most-needed topics for your system and assign each a
level-2 heading in this section (e.g. 8.1, 8.2 etc)._

=== _++<++Concept 1++>++_

_++<++explanation++>++_

=== _++<++Concept 2++>++_

_++<++explanation++>++_

…​

=== _++<++Concept n++>++_

_++<++explanation++>++_

WARNING: DO NOT ATTEMPT to cover all of the topics of the aforementioned diagram.

*Further Information*

_Some topics within systems often concern multiple building blocks,
hardware elements or development processes. It might be easier to
communicate or document such *cross-cutting* topics at a central
location, instead of repeating them in the description of the concerned
building blocks, hardware elements or development processes.
Certain concepts might concern *all* elements of a system, others might
only be relevant for a few. In the diagram above, logging concerns all
three components, whereas security is relevant only for two components._

_See_ https://docs.arc42.org/section-8/[Concepts] _in the arc42
documentation._

.Cross-Cutting Concepts
====

* Identity, Authentication and Authorisation
* Audit and Traceability
* Integration Resilience
* Data Privacy and Retention
* Logging, Monitoring and Observability
 User-experience consistency across the merged web app shell
